## Variables
@popupId = 30
@itemId = 925

### 팝업 좋아요 토글 (contentType : popup)
POST http://localhost:8080/api/v1/likes
Content-Type: application/json
Authorization: {{Authorization}}
Cookie: {{Cookie}}

{
  "contentId": {{popupId}},
  "contentType": "popup"
}

### 굿즈 좋아요 토글 (contentType : item)
POST http://localhost:8080/api/v1/likes
Content-Type: application/json
Authorization: {{Authorization}}
Cookie: {{Cookie}}

{
  "contentId": {{itemId}},
  "contentType": "item"
}

### 타입별 좋아요한 컨텐츠 목록 조회 (contentType : popup)
GET http://localhost:8080/api/v1/likes?contentType=popup
Authorization: {{Authorization}}
Cookie: {{Cookie}}

### 타입별 좋아요한 컨텐츠 목록 조회 (contentType : item)
GET http://localhost:8080/api/v1/likes?contentType=item
Authorization: {{Authorization}}
Cookie: {{Cookie}}
