name: CD

# main 브랜치 PR 발생 시 실행
on:
  pull_request:
    branches:
      - main

# 환경변수
env:
  ECR_URL: ${{secrets.ECR_URL}}

jobs:
  # develop 브랜치 체크
  check:
    runs-on: ubuntu-latest
    steps:
      # 브랜치 이동
      - name: branch checkout
        uses: actions/checkout@v4

      # PR 올린 브랜치가 develop 브랜치인지 검증
      - name: verity target branch
        run: |
          if [ "${{github.head_ref}}" != "develop" ]; then
            echo "develop 브랜치만 main 브랜치에 PR 가능"
            exit 1
          fi

  # main 브랜치에 merge
  merge:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: change main branch
        uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: '0'

      # main 브랜치에 develop 브랜치를 merge, main 브랜치 push
      - name: merge the dev into the main and push changes
        run: |
          git config --global user.name "ydh5017"
          git config --global user.email "ydh5017@naver.com"
          git merge origin/develop --no-edit
          git push origin main
        env:
          github_token: ${{ secrets.REPO_KEY }}

  # 배포
  deploy:
    runs-on: ubuntu-latest
    needs: merge

    steps:
      # main 브랜치 체크아웃
      - name: checkout main branch
        uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: '0'

      # JDK 17 설치
      - name: JDK 17 setup
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: "adopt"

      # gradlew 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # build
#      - name: Build with Gradle Wrapper
#        run: ./gradlew clean build --no-build-cache
#      - name: Clear Gradle Cache
#        run: rm -rf ~/.gradle/caches/

      - name: Build with Gradle
        run: ./gradlew clean build --stacktrace

      # Docker 이미지 생성
      - name: Docker build
        run: docker build . --platform linux/amd64 -f docker/Dockerfile -t ${{ env.ECR_URL }}:latest
  
      # AWS CLI 설치
      - name: AWS-cli setup
        run: |
          sudo apt install unzip
          sudo curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          sudo unzip awscliv2.zip
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update

      # AWS 연결설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY}}
          aws-region: ${{ secrets.AWS_REGION}}

      # ECR login
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Docker image upload and setting deploy files
      - name: AWS ECR upload and setting deploy files
        id: build-image
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION}} | docker login --username AWS --password-stdin ${{ env.ECR_URL }}
          docker push ${{ env.ECR_URL }}:latest 
          echo "image= ${{ env.ECR_URL }}:latest" >> $GITHUB_OUTPUT
          mkdir scripts
          touch scripts/deploy.sh
          echo "aws ecr get-login-password --region ${{ secrets.AWS_REGION}} | docker login --username AWS --password-stdin ${{ secrets.ECR_URL }}" >> scripts/deploy.sh
          echo "docker pull ${{ secrets.ECR_URL }}:latest" >> scripts/deploy.sh
          echo "docker run -d -p 8080:8080 \
                -e SERVER_PORT=${{ secrets.SERVER_PORT }} \
                -e DATASOURCE_URL=${{ secrets.DATASOURCE_URL }} \
                -e DATASOURCE_USERNAME=${{ secrets.DATASOURCE_USERNAME }} \
                -e DATASOURCE_PASSWORD=${{ secrets.DATASOURCE_PASSWORD }} \
                -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
                -e ACCESS_TOKEN_TTL=${{ secrets.ACCESS_TOKEN_TTL }} \
                -e REFRESH_TOKEN_TTL=${{ secrets.REFRESH_TOKEN_TTL }} \
                -e DDL_AUTO=${{ secrets.DDL_AUTO }} \
                -e REDIS_HOST=${{ secrets.REDIS_HOST }} \
                -e REDIS_PORT=${{ secrets.REDIS_PORT }} \
                --restart always \
                --memory=\"922m\" \
                --name ezpz-user ${{ secrets.ECR_URL }}:latest" >> scripts/deploy.sh
          
      # deploy files upload to S3
      - name: upload to S3
        run: |
          zip -r ezpz-user-latest.zip ./scripts appspec.yml
          aws s3 cp --region ${{ secrets.AWS_REGION }} --acl private ./ezpz-user-latest.zip s3://${{ secrets.AWS_BUCKET_NAME }}/scripts/

      # start deploy
      - name: start deploy
        run: |
          aws deploy create-deployment --application-name ezpz-admin-deploy \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name ezpz-user \
          --s3-location bucket=${{ secrets.AWS_BUCKET_NAME }},bundleType=zip,key=scripts/ezpz-user-latest.zip
